### ISSUE TITLE
Colm and Ragel via CMake

### ISSUE THREAD

**Issue by podsvirov** [gsauthof/cmake-ragel#1]
Hi @gsauthof, looks like you interested build Ragel via CMake.
I have good news for you! Today you can build Colm and then Ragel via CMake.
I contact with Adrian D. Thurston and he merge my changes (add CMake project) to Colm and Ragel projects.

It's easy: build and install Colm via CMake, then use `colm` package to build and install Ragel via CMake.

Any questions and suggestions?

**Comment by gsauthof** [comment]
In the environments where I use ragel it's usually not a problem to install it via a package manager (think: `dnf install ragel`).

I'm interested in having a cmake module readily available that deals with calling ragel from your project's `CMakeLists.txt.

Such that not everybody who needs to call ragel during the build process has to re-invent the wheel. Similar to how cmake comes with support for other code generators (e.g. flex/bison).

Does ragel nowadays comes with some cmake module that provides such integration?

**Comment by podsvirov** [comment]
I think the most universal solution is to learn the [add_custom_command](https://cmake.org/cmake/help/latest/command/add_custom_command.html).
For some people this is difficult and your project will definitely be claimed.
